### ISSUE TITLE
Missing section "VoID testing on locally installed subsets of IDSM"

### ISSUE THREAD

**Issue by galgonek** [biohackathon-swat4hcls/2024-hack4-hack8#5]
@egonw, Please, where should the paper be primarily edited? I added the section "VoID testing on locally installed subsets of IDSM" to [hackmd.io](https://hackmd.io/@yVAYnqXiSWS8SfLIa0ttEw/BiohackSWAT4HCLS2024_SPARQLAI) at the beginning of March, but I do not see it here on github. Thank you very much in advance.

**Comment by egonw** [comment]
Okay, thanks! I'll copy it in. I said I'd do that. I did not notice this yesterday

**Comment by egonw** [comment]
A compared the content with HackMD and I think I have all the new content now.
